-- Lost & Found Information System (lf_db)
-- Basic schema (beginner-friendly)

CREATE DATABASE IF NOT EXISTS `if0_40581770_lf_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `if0_40581770_lf_db`;

-- Users
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(160) DEFAULT NULL,
  `username` VARCHAR(80) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL, -- store HASH from PHP password_hash()
  `role` ENUM('admin','staff') NOT NULL DEFAULT 'staff',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `avatar` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed admin user: replace with a real hash generated by PHP's password_hash
-- Example: password_hash('admin123', PASSWORD_DEFAULT)
INSERT INTO `users` (`name`,`email`,`username`,`password`,`role`) VALUES
('Administrator','admin@example.com','admin','$2y$10$REPLACE_WITH_REAL_HASH','admin');

-- Categories
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(120) NOT NULL,
  `description` TEXT,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO `categories` (`name`,`description`) VALUES
('Electronics','Phones, laptops, earphones, etc.'),
('Bags','Backpacks, purses, totes'),
('Documents','IDs, licenses, cards'),
('Clothing','Jackets, hats, scarves');

-- Items
DROP TABLE IF EXISTS `items`;
CREATE TABLE `items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `category_id` INT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT,
  `photo` VARCHAR(255) DEFAULT NULL,
  `status` ENUM('pending','published','claim_pending','claimed') NOT NULL DEFAULT 'pending',
  `finder_name` VARCHAR(120) DEFAULT NULL,
  `finder_contact` VARCHAR(160) DEFAULT NULL,
  `location_found` VARCHAR(200) DEFAULT NULL,
  `date_found` DATE DEFAULT NULL,
  `approved_by` INT DEFAULT NULL,
  `approved_at` DATETIME DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE RESTRICT,
  FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
);

-- Messages
DROP TABLE IF EXISTS `messages`;
CREATE TABLE `messages` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(160) NOT NULL,
  `subject` VARCHAR(200) DEFAULT NULL,
  `message` TEXT NOT NULL,
  `read_at` DATETIME DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Pages (content blocks)
DROP TABLE IF EXISTS `pages`;
CREATE TABLE `pages` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `slug` VARCHAR(80) NOT NULL UNIQUE,
  `title` VARCHAR(160) NOT NULL,
  `content_html` MEDIUMTEXT,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO `pages` (`slug`,`title`,`content_html`) VALUES
('home','Welcome to Lost & Found','<p>Browse unclaimed items and help return them to their owners.</p>'),
('about','About Us','<p>We simplify lost and found management and connect people with their belongings.</p>'),
('contact','Contact Us','<p>Reach out with questions or to report found items.</p>'),
('terms','Terms & Conditions','<p>By using this system, you agree to submit accurate information and understand that administrators may approve or remove content at their discretion.</p>'),
('privacy','Privacy Policy','<p>We store minimal data to operate the system and do not share it with third parties. You may request deletion of your messages.</p>');

-- Settings (key-value)
DROP TABLE IF EXISTS `settings`;
CREATE TABLE `settings` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `skey` VARCHAR(120) NOT NULL UNIQUE,
  `svalue` TEXT
);

INSERT INTO `settings` (`skey`,`svalue`) VALUES
('site_name', 'Lost & Found Information System'),
('org_name', 'Campus Services');

-- Claims (requests by real owners to claim items)
DROP TABLE IF EXISTS `claims`;
CREATE TABLE `claims` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `item_id` INT NOT NULL,
  `claimant_name` VARCHAR(120) NOT NULL,
  `claimant_contact` VARCHAR(160) NOT NULL,
  `evidence_text` TEXT,
  `evidence_file` VARCHAR(255) DEFAULT NULL,
  `status` ENUM('new','approved','rejected','fulfilled') NOT NULL DEFAULT 'new',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE CASCADE
);
